name: 'AWS SAM Deploy with config file'
description: 'Deploys AWS SAM Stack'
author: 'Jobin Mathew <jobin.mathew@icemedial.com.au>'
branding:
  icon: 'upload-cloud'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
